### ISSUE TITLE
Not working in Kitkat, Getting following error

### ISSUE THREAD

**Issue by appukrb** [saulmm/From-design-to-Android-part1#5]
08-18 07:41:16.141 4210-4210/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.saulmm.cui, PID: 4210
                                                 android.view.InflateException: Binary XML file line #84: Error inflating class android.widget.ViewSwitcher
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:621)
                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:164)
                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670)
                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:148)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                     at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:116)
                                                     at com.saulmm.cui.databinding.FragmentOrderFormBinding.inflate(FragmentOrderFormBinding.java:192)
                                                     at com.saulmm.cui.databinding.FragmentOrderFormBinding.inflate(FragmentOrderFormBinding.java:189)
                                                     at com.saulmm.cui.OrderDialogFragment.onCreateView(OrderDialogFragment.java:105)
                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:595)
                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:164) 
                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670) 
                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:148) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                     at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:116) 
                                                     at com.saulmm.cui.databinding.FragmentOrderFormBinding.inflate(FragmentOrderFormBinding.java:192) 
                                                     at com.saulmm.cui.databinding.FragmentOrderFormBinding.inflate(FragmentOrderFormBinding.java:189) 
                                                     at com.saulmm.cui.OrderDialogFragment.onCreateView(OrderDialogFragment.java:105) 
                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189) 
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757) 
                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355) 
                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146) 
                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098) 
                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008) 
                                                     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710) 
                                                     at android.os.Handler.handleCallback(Handler.java:733) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x10c000d
                                                     at android.content.res.Resources.getValue(Resources.java:1123)
                                                     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2314)
                                                     at android.content.res.Resources.getAnimation(Resources.java:963)
                                                     at android.view.animation.AnimationUtils.loadInterpolator(AnimationUtils.java:270)
                                                     at android.view.animation.Animation.setInterpolator(Animation.java:391)
                                                     at android.view.animation.Animation.<init>(Animation.java:255)
                                                     at android.view.animation.AnimationSet.<init>(AnimationSet.java:81)
                                                     at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:113)
                                                     at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:91)
                                                     at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:72)
                                                     at android.widget.ViewAnimator.setInAnimation(ViewAnimator.java:315)
                                                     at android.widget.ViewAnimator.<init>(ViewAnimator.java:59)
                                                     at android.widget.ViewSwitcher.<init>(ViewSwitcher.java:55)
                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:595) 
                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:164) 
                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670) 
                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:148) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                     at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:116) 
                                                     at com.saulmm.cui.databinding.FragmentOrderFormBinding.inflate(FragmentOrderFormBinding.java:192) 
                                                     at com.saulmm.cui.databinding.FragmentOrderFormBinding.inflate(FragmentOrderFormBinding.java:189) 
                                                     at com.saulmm.cui.OrderDialogFragment.onCreateView(OrderDialogFragment.java:105) 
                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189) 
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757) 
                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355) 
                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146) 
                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098) 
                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008) 
                                                     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710) 
                                                     at android.os.Handler.handleCallback(Handler.java:733) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by meparam** [comment]
Just remove the bold highlighted text from both the animation file  ( android:inAnimation=anim/slide_in_right
android:outAnimation=anim/slide_out_left)  
 
xml file:

<?xml version="1.0" encoding="utf-8"?>
<set
    xmlns:android="http://schemas.android.com/apk/res/android"
    **android:interpolator="@android:interpolator/fast_out_slow_in"**
    >

    <translate
        android:duration="@android:integer/config_mediumAnimTime"
        android:fromXDelta="100%p"
        android:toXDelta="0"
        />

    <alpha
        android:duration="@android:integer/config_mediumAnimTime"
        android:fromAlpha="0.0"
        android:toAlpha="1.0"
        />
</set>
